name: TEST_1
# on:
#   push: # enabling push event on master branch to fire the workflow
#     branches:
#       - main
on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '55 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout out current code using public action
        uses: actions/checkout@v2
      - name: get the list of files in our current directory and its subdirectory
        run: | # this | enables us to multiple commands, good for formatting
          pwd
          ls -alR
          npm start
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: print current files # this steps won't be showing any files as we didn't checkout our codes
        run: |
          pwd
          ls -alR
